services:
    database:
        container_name: backend-database
        image: postgres:latest
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

        environment:
            POSTGRES_PASSWORD: "admin"
            POSTGRES_USER: "postgres"

        ports:
            - "5432:5432"
    backend-api:
        container_name: backend-api
        depends_on:
            database:
                condition: service_healthy

        build: .
            
        ports:
            - "3000:3000"