# Render Blueprint for NodeJs.
services:
    - type: web
      plan: free
      name: backend-api
      runtime: node
      repo: https://github.com/felipectrevisol/backend-service
      buildCommand: "npm install"
      startCommand: node server.js
      envVars:
          - key: DATABASE_URL
            fromDatabase: 
                name: backend-database
                property: connectionString
databases:
    - name: backend-database
      plan: free