openapi: 3.0.1
info:
    title: API de Contatos.
    description: Essa API traz funcionalidades para apresentar informações de contatos cadastrados.
    version: 1.0.0
    termsOfService: https://github.com/felipectrevisol/backend-service/blob/main/README.md
    contact:
        name: Felipe Canto Trevisol
        email: contato.@exemplo.com
        url: https://github.com/felipectrevisol
    license:
        name: GPLv3
        url: https://www.gnu.org/licenses/quick-guide-gplv3.pt-br.html
externalDocs:
    description: GitHub README
    url: https://github.com/felipectrevisol/backend-service/blob/main/README.md
servers:
    - url: http://localhost:3000/v1/
      description: Localhost
paths:
    /contact/all:
        get:
            summary: A lista de todos os contatos até agora cadastrados.
            tags:
                - Contatos
            responses:
                200:
                    description: Secesso.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            description: identificador do contato.
                                        name:
                                            type: string
                                            description: Nome do contato.
                                        lastName:
                                            type: string
                                            description: Sobrenome do contato.
                                        createdAt:
                                            type: string
                                            description: Data que foi criado o registro.
                                        updatedAt:
                                            type: string
                                            description: Data que da última alteração do registro.
                                        PhoneNumbers:
                                            type: array
                                            items:
                                                type: object
                                                properties:
                                                    id:
                                                        type: integer
                                                        description: identificador do telefone.
                                                    number:
                                                        type: string
                                                        description: identificador do telefone.
                                                    createdAt:
                                                        type: string
                                                        description: Data que foi criado o registro.
                                                    updatedAt:
                                                        type: string
                                                        description: Data que da última alteração do registro.
                                                    ContactId:
                                                        type: integer
                                                        description: identificador do contato.
    /contact/{id}:
        get:
            summary: Um contato identificado por id.
            parameters:
                - in: path
                  name: id
                  type: integer
                  required: true
                  description: Id do contato.
            tags:
                - Contatos
            responses:
                200:
                    description: Secesso.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            description: identificador do contato.
                                        name:
                                            type: string
                                            description: Nome do contato.
                                        lastName:
                                            type: string
                                            description: Sobrenome do contato.
                                        createdAt:
                                            type: string
                                            description: Data que foi criado o registro.
                                        updatedAt:
                                            type: string
                                            description: Data que da última alteração do registro.
                                        PhoneNumbers:
                                            type: array
                                            items:
                                                type: object
                                                properties:
                                                    id:
                                                        type: integer
                                                        description: identificador do telefone.
                                                    number:
                                                        type: string
                                                        description: identificador do telefone.
                                                    createdAt:
                                                        type: string
                                                        description: Data que foi criado o registro.
                                                    updatedAt:
                                                        type: string
                                                        description: Data que da última alteração do registro.
                                                    ContactId:
                                                        type: integer
                                                        description: identificador do contato.
    /contact/{id}/with/phone/{phoneNumber}:
        get:
            summary: Um contato identificado por id e por número de telefone.
            parameters:
                - in: path
                  name: id
                  type: integer
                  required: true
                  description: Id do contato.
                - in: path
                  name: phoneNumber
                  type: string
                  required: true
                  description: Número do telefone do contato.
            tags:
                - Contatos
            responses:
                200:
                    description: Secesso.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            description: identificador do contato.
                                        name:
                                            type: string
                                            description: Nome do contato.
                                        lastName:
                                            type: string
                                            description: Sobrenome do contato.
                                        createdAt:
                                            type: string
                                            description: Data que foi criado o registro.
                                        updatedAt:
                                            type: string
                                            description: Data que da última alteração do registro.
                                        PhoneNumbers:
                                            type: array
                                            items:
                                                type: object
                                                properties:
                                                    id:
                                                        type: integer
                                                        description: identificador do telefone.
                                                    number:
                                                        type: string
                                                        description: identificador do telefone.
                                                    createdAt:
                                                        type: string
                                                        description: Data que foi criado o registro.
                                                    updatedAt:
                                                        type: string
                                                        description: Data que da última alteração do registro.
                                                    ContactId:
                                                        type: integer
                                                        description: identificador do contato.